version: '3.9'
services:
  running_on_dart:
    image: ghcr.io/nyxx-discord/running_on_dart:4.10.1
    container_name: running_on_dart
    restart: unless_stopped
    depends_on:
      - db
    env:
      - stack.env

  db:
    image: postgres:17
    container_name: running_on_dart_db
    restart: unless_stopped
    env:
      - stack.env
    volumes:
      - "rod_db_17:/var/lib/postgresql/data"

volumes:
  rod_db_17:
  rod_sessions:
