services:
  running_on_dart:
    build:
      context: .
      target: dev
    container_name: running_on_dart
    env_file:
     - .env
    ports:
      - "8088:8088"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: running_on_dart_db
    ports:
      - "13323:5432"
    env_file:
     - .env
    volumes:
      - "rod_db_v5:/var/lib/postgresql/data"

volumes:
  rod_db_v5:
