version: '3.9'
services:
  running_on_dart:
    image: ghcr.io/nyxx-discord/running_on_dart:4.4.1
    container_name: running_on_dart
    env_file:
     - .env
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:13.5
    container_name: running_on_dart_db
    restart: always
    env_file:
     - .env
    volumes:
      - "rod-new_rod_db:/var/lib/postgresql/data"

volumes:
  rod-new_rod_db:
    external: true
