version: '3.9'
services:
  running_on_dart:
    image: ghcr.io/nyxx-discord/running_on_dart:3.2.0
    container_name: running_on_dart
    env_file:
     - .env
    links:
      - db
      - lavalink
    depends_on:
      - db
      - lavalink

  db:
    image: postgres:13.5
    container_name: running_on_dart_db
    restart: always
    env_file:
     - .env
    volumes:
      - "rod-new_rod_db:/var/lib/postgresql/data"

  lavalink:
    image: fredboat/lavalink:master
    container_name: running_on_dart_lavalink
    restart: always
    expose:
      - 2333
    volumes:
     - /services/rod-lavalink.yml:/opt/Lavalink/application.yml:ro

volumes:
  rod-new_rod_db:
    external: true
