global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rod'
    scrape_interval: 5s
    static_configs:
      - targets: ['running_on_dart:8080']
